[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \   'colorscheme': 'nightowl',
  \   'component': {
  \     'readonly': '%{&readonly?"тнд":""}',
  \   },
  \   'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'readonly', 'filename', 'modified' ],
  \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
  \   }
  \ }

  set laststatus=2
  set noshowmode
'''
