[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# [[plugins]]
# repo = 'lambdalisue/nerdfont.vim'
# 
# [[plugins]]
# repo = 'lambdalisue/fern-renderer-nerdfont.vim'
# hook_add='''
#   let g:fern#renderer = "nerdfont"
# '''
# 
# [[plugins]]
# repo = 'lambdalisue/glyph-palette.vim'
# hook_add = '''
#   augroup my-glyph-palette
#     autocmd! *
#     autocmd FileType fern call glyph_palette#apply()
#   augroup END
# '''
