[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  let g:gitgutter_async = 1
  let g:gitgutter_sign_modified = 'm'

  nnoremap gp :GitGutterPreviewHunk<CR>

  highlight GitGutterAdd ctermfg=green
  highlight GitGutterChange ctermfg=blue
  highlight GitGutterDelete ctermfg=red

  set updatetime=2000
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'APZelos/blamer.nvim'
hook_add = '''
  let g:blamer_enabled = 1
  let g:blamer_show_in_visual_modes = 1
  let g:blamer_show_in_insert_modes = 0
  let g:blamer_prefix = ' > '
  let g:blamer_template = '<committer>, <committer-time> • <summary>'
  let g:blamer_date_format = '%y/%m/%d %H:%M'
  let g:blamer_relative_time = 0
'''
